### ISSUE TITLE
IOList BIFs

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#153]
- [ ] `iolist_size/1`
- [ ] `iolist_to_binary/1`
- [ ] `iolist_to_iovec/1`

**Comment by mlwilkerson** [comment]
I'm going to try my hand at this one.

**Comment by mlwilkerson** [comment]
@KronicDeth Should I be trying to add an `iolist` type to the `TypedTerm` enum? And possibly also an `iovec` type? Both are mentioned as types in the [Erlang docs](http://www.erlang.org/doc/man/erlang.html#iolist_to_binary-1) related to these IOList BIFs. However, they aren't cited in Erlang's set of [Term types](http://www.erlang.org/doc/reference_manual/data_types.html#terms). Since they can both be expressed in terms of list (which needs to include improper lists) or binary, maybe it's not necessary for them to have their own `TypedTerm`. 🤔

**Comment by KronicDeth** [comment]
You’re confusing the user level Erlang and Elixir types with the [tagged types](https://blog.stenmans.org/theBeamBook/#CH-TypeSystem) that the VMs use.  TypedTerm is for the tagged types, which don’t include iovec and iolist.

**Comment by mlwilkerson** [comment]
Thanks. I'm sure I'm confusing more than _that_ as I climb the learning curve, but I'm sure your linked doc will help.

**Comment by KronicDeth** [comment]
Resolved by #362
