### ISSUE TITLE
Split Term into copyable and non-copyable variants

### ISSUE THREAD

**Issue by hansihe** [lumen/lumen#271]
As is, the `Term` type is used both for term headers on the heap, and for immediate terms that are passed around the runtime.

Because this term type implements copy, if a non-immediate term located on the heap is handled wrong, it can be dereferenced and copied, resulting in memory safety issues.

I suggest splitting the `Term` type we have into two separate variants.
* `HeapTerm` does not implement copy, and is what you get a reference to when handling terms on the heap. A `HeapTerm` would have methods to convert it to a `Term` while making sure it is an immediate term.
* `Term` does implement copy. It can only contain immediate terms, so copying does not cause any issues. `Term` would be freely convertible to a `HeapTerm` without needing to do any checks at all.

It should be noted that two terms would still contain the exact same term tagging scheme, and casting between pointers of the two would be fine. They are both simply newtypes containing a single machine word.

This change should not affect runtime efficiency at all, it simply prevents a whole suite of issues that I believe Luke has been struggling with.

**Comment by bitwalker** [comment]
I agree there is an issue here, and that we should try and find a solution that improves the safety of code which operates on raw `Term`. 

To clarify, the main issue is copying a header term unintentionally and then using the address of that term to access its data which is expected to be found in the memory immediately following the header, but which now points into some arbitrary area of memory due to the copy. It is particularly bad when the copy and the access are not in the same section of code, i.e. at some random point later on during execution, things explode due to the invalid memory access.

I'm a bit concerned though that code which uses one type or the other bleeds together, leading to a different issue, which is that you end up just juggling a different kind of unsafe/implicit code. A couple of potential alternatives that may be worth looking at instead:

- Removing `Copy` from `Term` entirely, and always require explicit cloning
- Use `Pin` or something like it to express that in some section of code, the inner `Term` is pinned in memory and cannot be copied except via explicit cloning. I think most problems occur in relatively small regions of code, so being able to restrict copies in the current region when accessing a term stored on a process heap would prevent the vast majority of issues while avoiding the need for a massive refactoring that I'm not sure will provide us a significant improvement to overall safety.

In any case, I suspect this is a non-trivial effort no matter how we go about it. While the current approach is very much a dangerous footgun, I'd rather not change it until we know that a.) we aren't painting ourselves into a corner, and b.) we meaningfully improve the safety of code that works with terms, i.e. we don't trade one kind of unsafety for another.

**Comment by bitwalker** [comment]
So, an update on this - I think I've basically solved this as part of my term refactoring work (#350).

With the changes made in that PR, there are very very few places that operate on a `Term` that isn't an immediate or a box by construction. The exceptions to that rule are all in unsafe code anyway that is unavoidable (namely the internals of the term encoding, and in the garbage collector). Now, any time we construct a boxed type `T`, we actually construct a `Boxed<T>` and pass that around instead. `Boxed<T>` has safe conversions to and from `Term`, and is `Deref` for `T`, as a result we never pass around a header `Term`, as you never construct one directly, and we never pass around `Header<T>` either, instead accessing the header via its `Boxed<T>` pointer.

There are some additional improvements to the garbage collector as well, to reduce the places where we ever deal with the `Term` type in an unsafe manner, primarily via the introduction of the `HeapIter` type, and the `Sweep` trait. The places where we directly construct a reference to a header `Term` are basically found in 5 places: `from_raw_term` in `HeapBin`, `Closure`, and `Tuple`, the implementation of `Sweep` for `*mut Term`, and the implementation of `HeapIter`.

So I'm going to close this issue for now, until we identify further improvements that we think are necessary.
