### ISSUE TITLE
Why not use the libllvm shipped with rustc?

### ISSUE THREAD

**Issue by bjorn3** [lumen/lumen#274]
On Linux for example you can find it at `$(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM.so`. This would save users the effort and time of compiling llvm themselves.

**Comment by bitwalker** [comment]
There are a few reasons. Rust uses its own fork of LLVM, and typically lags behind mainline (they only recently started upgrading to LLVM 9, not sure when that will make it into nightly). The larger issue is that the `libLLVM.so` shipped with Rust isn't necessarily the same as any other `libLLVM.so`, as that shared object contains whatever components Rust was built with, with the configuration they used to build it. We want control over what components we ship with (which does in fact include some things that Rust does not ship), as well as how those components are built, and not be tied to whatever version and patches that Rust requires.

When the compiler backend gets merged, we can review and see if it can be used as a fallback option, but since LLVM is only required to build the compiler backend (and any components that depend on it, which will ultimately only be the `lumen` executable), I don't consider it to be unreasonable to have contributors to those components install LLVM. Especially since with proper set up, subsequent builds after the initial first-time build can be very fast. I also have a helper script to make installing/updating extremely easy to do for those that aren't familiar with LLVM and don't otherwise wish to manage it themselves.

For those that aren't working on components that directly depend on LLVM, they shouldn't need to install it at all for working on patches/running tests, only for building the full compiler. This is where we could potentially support the Rust LLVM as a fallback if a "proper" LLVM install is not present - but I suspect that isn't going to be an option due to the lack of components we depend on (namely the linker bits).

I'm going to close this for now, but I will keep it in mind as the codegen bits get wrapped up, and if it is possible, I will make it a fallback option for easier project set up :)
