### ISSUE TITLE
Questions about the project.

### ISSUE THREAD

**Issue by Tzelon** [lumen/lumen#333]
Hey everyone.
I'm very interested in the project, and I want to help.
My questions are
1. Where can I be most helpful? I have basic Rust knowledge.
2. How would you expect others to use Lumen in the end product? each dev needs to write Rust code?

Thanks

**Comment by hansihe** [comment]
Hello!

1. For now, finding a BIF in the issues and working on implementing it is probably the easiest way to get involved.

    Once we make the compiler with the WASM target easy to use, we need help from the community to experiment with various ways to write web apps with Lumen. We expect there to be a fair amount of experimentation before arriving on a nice framework, and this is something we need help with.

2. The average developer using Lumen would not need to write any Rust in the same way that the average developer of the BEAM is not expected to write any C. The development experience with Lumen will be writing an app in a BEAM language, and running the Lumen compiler on that app to compile it to a binary.

Really cool to see interest! If you need help with anything, all of the core team hang out in the #lumen channel on the Elixir Slack.

**Comment by Tzelon** [comment]
Cool! 
Can you recommend an easy, getting started BIF to do? 
I will join the channel :)

**Comment by KronicDeth** [comment]
@Tzelon anything in https://github.com/lumen/lumen/milestone/4 that doesn't already have someone assigned would be a good start.

* https://github.com/lumen/lumen/issues/153 are probably the easiest.
  Do one BIF per PR, not all 3 if you could.  We'd resolve the issue once the last BIF is completed in the set.
* https://github.com/lumen/lumen/issues/159 seems easy too since it is probably just keeping an atomic counter somewhere.  You'll need to study the OTP C code to understand how the different flags affect the output.
