### ISSUE TITLE
Discussion: Integrating Codegen and Runtime

### ISSUE THREAD

**Issue by bitwalker** [lumen/lumen#388]
As I mentioned in the call today, I'd like to resolve some outstanding items needed to link up generated code with the runtime.

## Items Needed

- [x] Lumen installer generates toolchain with target-specific libraries for linking with generated code
- [x] Linker knows about runtime crates and which to link for each target
- [x] Atom table initialized from constants gathered during compilation at runtime start
- [ ] Codegen generates metadata for scheduler so it knows how to start the compiled application, i.e. it knows what function to call for `init:start` (See `Init`)
- [ ] Scheduler needs to know when a process has yielded control due to a request, due to an error being thrown but not caught, or due to process exit (both normally or otherwise). (See `Signals`)
- [ ] Runtime needs the ability to construct Erlang-style stack traces. We need to store the necessary metadata somewhere, and provide a way to access it from the runtime. (See `Traces`)
- [ ] Scheduler needs to know how to call into generated code when resuming a process (See `Calling Convention`, `Init`)

## Init

As a refresher, here's the basic startup routine for an Erlang application:

- VM starts and initializes the runtime
- VM hands control to Erlang by invoking/starting `init`
- `init` performs core initialization, reads the boot script containing instructions on how to start the system (i.e. which applications to load/start, in what order, and what functions to call to do so)
- `init` starts the `application_controller`
- `init` walks the boot script, collaborating with the `application_controller` to load/start applications in the order given; each application is started by starting an `application_master` for that application.
- each `application_master` starts its application by invoking the `start/2` callback (and others as well)

We will want to mirror this process more or less. In the near term though, we don't have all of the OTP infrastructure in place, we're working with pure Erlang + our runtime, so things differ a bit. Here's more or less what I'm operating on as a starting point:

- Core runtime starts (liblumen_crt - handles calling into the target-specific runtime crate, initializes the atom table)
- Core runtime calls the target-specific runtime entry point (lumen_web/lumen_runtime). This starts the scheduler and performs any other necessary initialization needed by the runtime.
- Scheduler reads the application metadata to obtain the function pointer for the "main" function of the generated code. This would correspond to the `init` module. The function takes no arguments and is responsible for kicking off execution of the Erlang part of the application.

So given a simple Erlang module:

```erlang
-module(init).
-export([main/0]).

main() ->
  io:format("~s\n", ["Hello world!"]).
```

The scheduler would essentially be invoking the function pointer corresponding to the `main/0` function. In this case, the function would just print "Hello world!", then signal to the scheduler that the process is exiting normally, which would result in the scheduler shutting down and the program terminating normally.

Down the road, when we start introducing the OTP libraries, _we_ will provide the `init` module, and it will perform the same kind of startup procedure that `init` in BEAM does.

I think this provides a nice foundation to build on. The key parts to decide are:

- What metadata is needed in the scheduler
- How does that metadata get generated/stored
- How does the scheduler access it

## Signals

In order for linking against the runtime to work at all, we need the ability to signal various conditions between the scheduler and the generated code which needs to branch based on those conditions.

- The scheduler needs to know when control returns from the process code whether it returned due to yielding voluntarily (or due to reduction count/garbage collection), whether the process threw an error that was not caught, or whether the process is exiting (normally or abnormally).
- The generated code needs to know that the scheduler wants it to yield after control returns from a call to the runtime. Likewise, the scheduler may want to signal an exit. When control is yielded to the scheduler, it can do these things without coordination, but when calling _into_ the runtime, the scheduler needs cooperation from the process.
- Beyond just signals, the generated code also needs to be able to monitor/maintain the reduction count on its own. In order to facilitate this, we would use a thread local that both the scheduler and the generated code can check/modify.

My feeling is that we would use a set of thread locals to facilitate these things:

- A thread local for the process signal, an enum which represents the different types of signals
- Thread locals for any signal metadata that is necessary for specific signal types (i.e. an error value for errors that bubble up to the scheduler)
- A thread local for the reduction count

## Calling Convention

Related to `Signals`, is the calling convention between our Rust runtime code, and the generated Erlang code.

If we decide _not_ to use thread locals to signal error conditions/yielding/etc., then the next alternative is to have an ABI/calling convention that allows for effective multi-value returns. In practice that means using a struct with a field to carry the error/status flag, plus one or more fields based on the function's "real" return type. Where this gets ugly is that we already need something like this to communicate function-specific errors, so combining both types of signals into one convention is not ideal.

"Global" signals aside, we can pretty trivially land on an FFI-safe `Result`/`Option` equivalent for use at our runtime boundaries. The `Option` case is actually the easiest, since we can make use of the none value/tag to represent the `None` variant. The presence of `None` could then be used to signal that an error occurred, where the error term itself is either stored in the process struct, or in a thread local (similar to `errno` for example).

Other than that, I think for the near term we'll use the C ABI for all functions - in the future we'll likely use a separate calling convention for Erlang functions, akin to `fastcc`, but I don't think we have enough information yet on how code will get called, and we can't call from Rust into `fastcc` code directly, at least not safely.

## Traces

To reiterate, there are two kinds of traces:

1. Erlang stack traces, i.e. what you see in error reports from SASL, etc. Displayed in Erlang term format, so easy to parse/understand for users. Matches what was happening from an Erlang perspective, but no relation to the actual thread of execution. Produced when something goes wrong in user code.
2. Native stack traces, i.e. not language-oriented, often shows a lot of frames for code you don't own but was called between frames of your own code. In the worse case, the names are mangled and barely readable. The closest thing to a source of truth about where your application was at when it failed. Produced when shit hits the fan in the runtime itself, or some natively-implemented code fails.

The Erlang code we're compiling generates debug symbols with locations that can be linked back to the original source code. Obtaining a native trace with those symbols is fairly easy (with some work to integrate libbacktrace, or something like it). On the other hand, obtaining an Erlang stack trace is not so easy. There is no easy way to get a trace of locations that correspond only to Erlang code.

Instead we have to construct one somehow. One approach is to maintain our own frame stack that is used solely for Erlang traces, but that isn't ideal - it introduces overhead during execution, and duplicates effort that we'd prefer to avoid duplicating. That said, it has the best chance of mirroring the traces like seen in BEAM.

The approach I would like to try though, is to leverage the debug symbols we generate + libbacktrace. When capturing a trace, we capture a native trace; and when formatting for display, or constructing a term representation, we walk the captured trace and only print symbols for Erlang code.  

A mixture of the two approaches could be to have the function prologue push a pointer to the frame metadata on to a stack set aside for Erlang traces. Capturing a trace would take a snapshot of the stack, and formatting/constructing it would follow a similar pattern as the native traces, by resolving the locations in the stack to their corresponding symbols/metadata.

In any case, this is pretty important for getting proper stack traces, but we can probably work around the absence of the functionality in the near term. I'd mostly like to land on a direction though sooner rather than later.

**Comment by KronicDeth** [comment]
> # Init

To make it most `init.erl` like, we could have the current version always call an `init:boot(BootArgs)` and only have `init:boot/1` support `-s`, which would be the MFA of the actual entry point in the `.erl` file for the one-file projects we want to support in the beginning.

This would also work with the way you said we'd need to support WebAssembly until we figure out the calling in from JS feature later.

Stepping back from `init:boot`.  BEAM actually has a `+i` flag where you could override the name `init` if you really felt like it and that is called by the preloaded module, `erl_init`, which does

https://github.com/erlang/otp/blob/2d2d78311aa803930d92aa962c823826a93ae7e7/erts/preloaded/src/erl_init.erl#L26-L41

```erlang
%% This gets the module name given by the +i option (default 'init')
%% and the list of command line arguments

-spec start(Mod, BootArgs) -> no_return() when
      Mod :: module(),
      BootArgs :: [binary()].
start(Mod, BootArgs) ->
    %% Load the static nifs
    zlib:on_load(),
    erl_tracer:on_load(),
    prim_buffer:on_load(),
    prim_file:on_load(),
    %% socket:on_load(), prim_net:on_load(),
    conditional_load(socket, [socket, prim_net]),
    %% Proceed to the specified boot module
    run(Mod, boot, BootArgs).
```

`erl_init.erl`'s `erl_init:start` is called from `erl_init.c`

https://github.com/erlang/otp/blob/master/erts/emulator/beam/erl_init.c#L433

```c
res = erl_spawn_system_process(&parent, am_erl_init, am_start, args, &so);
```

in [the `erl_first_process_otp` function](https://github.com/erlang/otp/blob/2d2d78311aa803930d92aa962c823826a93ae7e7/erts/emulator/beam/erl_init.c#L400-L440)

```c
static Eterm
erl_first_process_otp(char* mod_name, int argc, char** argv)
{
    int i;
    Eterm args;
    Eterm res;
    Eterm* hp;
    Process parent;
    ErlSpawnOpts so;
    Eterm boot_mod;

    /*
     * We need a dummy parent process to be able to call erl_create_process().
     */

    erts_init_empty_process(&parent);
    erts_proc_lock(&parent, ERTS_PROC_LOCK_MAIN);

    hp = HAlloc(&parent, argc*2 + 4);
    args = NIL;
    for (i = argc-1; i >= 0; i--) {
	int len = sys_strlen(argv[i]);
	args = CONS(hp, new_binary(&parent, (byte*)argv[i], len), args);
	hp += 2;
    }
    boot_mod = erts_atom_put((byte *) mod_name, sys_strlen(mod_name),
                             ERTS_ATOM_ENC_LATIN1, 1);
    args = CONS(hp, args, NIL);
    hp += 2;
    args = CONS(hp, boot_mod, args);

    so.flags = erts_default_spo_flags;
    so.opts = NIL;
    res = erl_spawn_system_process(&parent, am_erl_init, am_start, args, &so);
    ASSERT(is_internal_pid(res));

    erts_proc_unlock(&parent, ERTS_PROC_LOCK_MAIN);
    erts_cleanup_empty_process(&parent);

    return res;
}
```

`erl_first_process_otp` is [called in `erl_start`](https://github.com/erlang/otp/blob/2d2d78311aa803930d92aa962c823826a93ae7e7/erts/emulator/beam/erl_init.c#L2305)

```
erts_init_process_id = erl_first_process_otp(init, boot_argc, boot_argv);
```

`erl_start` [takes `main`-style arguments](https://github.com/erlang/otp/blob/2d2d78311aa803930d92aa962c823826a93ae7e7/erts/emulator/beam/erl_init.c#L1273)

```
erl_start(int argc, char **argv)
```

`erl_start` does all the business of [parsing the commandline arguments](https://github.com/erlang/otp/blob/2d2d78311aa803930d92aa962c823826a93ae7e7/erts/emulator/beam/erl_init.c#L1327-L2227) before starting the [initing the system itself](https://github.com/erlang/otp/blob/2d2d78311aa803930d92aa962c823826a93ae7e7/erts/emulator/beam/erl_init.c#L2288-L2297)

```
erl_init(ncpu,
	     proc_tab_sz,
	     legacy_proc_tab,
	     port_tab_sz,
	     port_tab_sz_ignore_files,
	     legacy_port_tab,
	     time_correction,
	     time_warp_mode,
	     node_tab_delete_delay,
	     db_spin_count);
```

Interestingly, that [first process is spawned](https://github.com/erlang/otp/blob/2d2d78311aa803930d92aa962c823826a93ae7e7/erts/emulator/beam/erl_init.c#L2305) before [the schedulers starts running](https://github.com/erlang/otp/blob/2d2d78311aa803930d92aa962c823826a93ae7e7/erts/emulator/beam/erl_init.c#L2366).   I'm not sure if that ordering is terribly important for us though.

From this walk through BEAM's startup code, I would say that it's not actually the schedulers that should be starting `init`, it's more that we should have a `start` entry point that deals with the commandline arguments (or their equivalent JSON object for WebAssembly like you thought up before ❤️ ), so that we can support an `+i` flag if necessary.  This `start` function would then start the schedulers however you've figured out to make that work across architectures since it differs in browsers vs native and the init process would be put on the primary scheduler's run queue.

> Scheduler reads the application metadata to obtain the function pointer for the "main" function of the generated code. This would correspond to the init module. The function takes no arguments and is responsible for kicking off execution of the Erlang part of the application.

I think it would better to stub this out in Rust and have it support the equivalent of `-s` or `-run` instead.  I'm assuming in the generated code that calls into the scheduler you can compile in `.rodata` that acts as arguments to `-s` passed to the `start` function.

Is `-s` and `-run` faking too much for this first pass?

**Comment by KronicDeth** [comment]
# How it works now in `lumen_runtime` and `examples/spawn-chain`

> # Signals

> * The scheduler needs to know when control returns from the process code whether it returned due to yielding voluntarily (or due to reduction count/garbage collection), whether the process threw an error that was not caught, or whether the process is exiting (normally or abnormally).

> yielding voluntarily

There is no voluntary yielding currently if you mean like BEAM BIFs that yield because they think they will take too long a timeslice.

In `spawn-chain` we do have the yielding due to waiting on a matching message

https://github.com/lumen/lumen/blob/3567ad87ef3eb751049d9b6b5a89e28253e8212f/examples/spawn-chain/src/elixir/chain/create_processes_2/label_2.rs#L119-L125

If we don't have the final integer to `receive` we `wait`, which sets the `Process` status` to `Status::Waiting`.  @hansihe intrinsics would be involved in the real version of [received check](https://github.com/lumen/lumen/blob/3567ad87ef3eb751049d9b6b5a89e28253e8212f/examples/spawn-chain/src/elixir/chain/create_processes_2/label_2.rs#L38-L115), of course

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/liblumen_alloc/src/erts/process.rs#L1007-L1011

> due to reduction count

The `code` functions mostly increment their reductions at the beginning

https://github.com/lumen/lumen/blob/d02696d005c1b456fb95b3882b6712a523eb8c7d/examples/spawn-chain/src/elixir/chain/dom_1.rs#L40

which increments the `AtomicU64` `run_reductions`

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/liblumen_alloc/src/erts/process.rs#L960-L962

`run_reductions` is an atomic because that's what BEAM used.  I don't see a problem moving it to a thread-local as those `run_reductions` are for a specific time slice as I needed to compare them to `MAX_REDUCTIONS_PER_RUN` in `is_reduced`:

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/liblumen_alloc/src/erts/process.rs#L964-L966

`is_reduced` is checked in `call_code`

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/liblumen_alloc/src/erts/process.rs#L1046-L1061

`call_code` is called at the bottom of every `code` fn to determine if the process is out of reductions and it needs to re-enter the run queue or it can keep going by calling the next `Code` pointer, which can either be a BIF or a label in the Erlang code.

https://github.com/lumen/lumen/blob/d02696d005c1b456fb95b3882b6712a523eb8c7d/examples/spawn-chain/src/elixir/chain/dom_1.rs#L45-L49

Currently, there is no difference in the return from `Process::call_code`, and therefore, `Code` function whether the process is out of reductions or just out of `Code` to run.

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/liblumen_alloc/src/erts/process.rs#L1056-L1059

They both return `Ok(())`

So, by default, processes are always requeued.

Once the process is done running either because of an exception from a `code::Result` or `Ok(())` we match on that

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/lumen_runtime/src/scheduler.rs#L132-L145

> garbage collection

The only `Err(exception)` we normally see above is `Alloc`, so `code::Result`'s `Err` is only used to signal garbage collection.

>  whether the process threw an error that was not caught, or whether the process is exiting (normally or abnormally).

This is handled in the next section of `Scheduler.run_once` after, the GC section above

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/lumen_runtime/src/scheduler.rs#L150-L159

`requeue` is a state machine state transition function

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/lumen_runtime/src/run/queues.rs#L72-L92

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/lumen_runtime/src/run/queues.rs#L115-L126

_This `Next::from_status` non-sense is to make it so we don't have to look at or move the data in `Status::Exiting` which includes RWLocks that really want to live for too long._

> whether the process is exiting (normally

Normal exits due to end-of-code are detected because there's no `Code` left to run when the process is supposed to be pushed back into the run queues

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/lumen_runtime/src/run/queues.rs#L81-L84

> whether the process is exiting (normally or abnormally).

Explicit exits are from the `Status::Exiting`.  They are not requeued and instead returned

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/lumen_runtime/src/run/queues.rs#L90

This is return is necessary because exiting processes need to propagate to their monitors and links

https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/lumen_runtime/src/scheduler.rs#L151-L157

The `Status::Exiting` can be set in a number of ways:

1. If the `native` of `code` returns `exception::Result` `Err` that is a `RuntimeException`, then `Process.exception` is called:

   https://github.com/lumen/lumen/blob/98a258c2ade2b8b46ab52f060950a537be8ccdcf/examples/spawn-chain/src/elixir/enum/reduce_3.rs#L102

   For all the `native_implemented_function` proc-macro using `native` function this is part of the generated `code`

   https://github.com/lumen/lumen/blob/7d286b93d1a839aa7de5fed7020bafc1bc39f300/lumen_runtime_macros/src/lib.rs#L278
https://github.com/lumen/lumen/blob/b254ff22fc2857f5d559cccf08bb589e51efe9aa/liblumen_alloc/src/erts/process/code.rs#L21-L35
2. A process calls the `exit/1` BIF, setting its own exit reason
3. A process calls the `exit/2` BIF setting its own exit reason or the exit reason for a different PID.

(2) and (3) both call `Process.exception`, so the code for (1) also works for (1).

The one caveat for handling exits from links or (3) (`exit(some_other_pid, :bad)`) exiting a process while it is in the run queue is that whether a process is exiting is checked after it is popped from the run queue, but before running it

https://github.com/lumen/lumen/blob/b254ff22fc2857f5d559cccf08bb589e51efe9aa/lumen_runtime/src/scheduler.rs#L131

> When calling into the runtime, the scheduler needs cooperation from the process. 

This is currently handled by all epilogues that call `process.exception` returning immediately in Rust, so that the `run_once` loop can see the process's status is now `Status::Exiting`.

https://github.com/lumen/lumen/blob/7d286b93d1a839aa7de5fed7020bafc1bc39f300/examples/spawn-chain/src/elixir/io/puts_1.rs#L48-L52

This only works because I haven't had to deal with `catch` blocks yet.  What these epilogues would have to do instead is something like `Process::call_code` that determines if there's a catch block to jump up to to handle the exception just set with `Process.exception`.

# How it can work with generated code

Mostly it's up to you to determine if the current `Status` enum is too annoying to work with over the FFI and you'd prefer some more broken up thread-locals since `Status` is a structured enum in Rust.

https://github.com/lumen/lumen/blob/b254ff22fc2857f5d559cccf08bb589e51efe9aa/liblumen_alloc/src/erts/process.rs#L1191-L1196

One thing you probably want to maintain is the status names as they come from the names reported in Observer and `Process.info`, so not having the distinction of `Runnable`, `Waiting`, and `Running` could lose insight people are use to seeing when debugging.

The `Exiting` status although temporary, is not so fast that isn't important.  There are BIFs in the BEAM code that work differently if a process is exiting.  I haven't audited all of them to verify that doing something to an exiting process would change observable behavior, but it is something to be aware of.

A process killed with `exit(pid, reason)` is in `Status::Exiting` immediately, but does not actually exit, propagate it's exit over links/monitor, or be deleted until it is popped from the run queue on the next pass. Only processes that exit themselves or throw an uncaught exception exit after that BIF returns.  Part of the reasoning for this difference as it ensures that a long chain of links doesn't have to completely resolve before the next process can run, instead only the first set of closest links have their statuses changed and it is up to their timeslices to act on that status change.

**Comment by KronicDeth** [comment]
> # Calling Convention

> In practice that means using a struct with a field to carry the error/status flag, plus one or more fields based on the function's "real" return type.

The `code::Result` is `Ok(()` or `Err(SystemException)`, but we really only expect `Ok(())` or `Err(SystemException::Alloc))` unless something bad happens with terms.  If that is the case it can be a C style enum of `SUCCESS` or `NEEDS_GC`, but we do really nice exceptions now because of anyhow, so it would be a bummer to lose that.

**Comment by KronicDeth** [comment]
> Calling Convention

Are we getting rid of the `push_stack` and `pop_stackn` function since the LLVM code may have put the Erlang term variables in true registers on native?  If so, I'll need to either remove or modify their usage in stuff like the `native_implemented_function`'s `code` function that peeks the values from the stack for `native` and `pop`s them all when it is safe to no longer worry about re-entrancy.

On that note, how are you handling re-entrancy with stack values and potential calls for GC?  Are you just peeking or is stuff off the stack?  I had to reason that all by hand and add some fallible `unwrap`s in `spawn-chain`.

**Comment by bitwalker** [comment]
## RE: Init

To be clear, the invocation of the "init" process would necessarily have to happen after configuration and initialization of the runtime is done - it is already required at the very least to initialize the atom table, and in the startup code I have for `lumen_runtime` at least, it also parses command-line arguments, configures debug logging, etc. Extending that to allow changing what function is invoked as init is fairly straightforward - but it is dependent on having a dispatch table so we can map MFAs to function pointers, which is not built out yet. So for now at least, a fixed entry point will be used, and the compiler will make sure that the top-level entry point for the generated code gets called from there. Extending that later when we start providing OTP libraries as part of the compiled application is straightforward.

That said, I'm not sure `-s`/`-run` is particularly useful when invoking a Lumen-compiled application. One of the reasons those flags are useful in BEAM is because the BEAM also handles finding and loading the .beam files which correspond to the MFA provided, so you effectively can use it as an ad-hoc scripting facility. Since Lumen compiles everything in at the beginning, the set of modules available to you is limited - and with LTO/DCE passes, you can't even be sure that the function you want to call even exists any more. Having a fixed entry point doesn't have that issue, and in fact acts as a "root", if you will, for LTO to trace the call graph of the application.

> I think it would better to stub this out in Rust and have it support the equivalent of -s or -run instead. I'm assuming in the generated code that calls into the scheduler you can compile in .rodata that acts as arguments to -s passed to the start function.

Could you clarify what you mean here? Which part is stubbed out - the scheduler invoking the `init` start function? We can generate data during codegen that can be passed to the scheduler during startup at runtime, which is more or less what I was planning for our .boot/.script equivalent functionality down the road - but I don't think it makes sense to do that for the `init` callback function, at least initially, to keep things simple.

> Is -s and -run faking too much for this first pass?

Yeah I think keeping it simple and just compiling a fixed entry point is the cleanest - especially since we don't have a global dynamic dispatch mechanism in place yet.

## RE: Signals

One thing I want to clarify here is that I'm not suggesting we need to remove the process status flag from the process struct; it could still be used for the runtime code that checks that status - the purpose of the thread local is to communicate status between the scheduler and the generated code, with one or the other being responsible for setting the process status via the appropriate runtime calls (i.e. if the generated code signals that an uncaught error occurred _in the generated code_, the scheduler would set the process flag; likewise for some of the signals). The generated code would use the thread local to access the process status without having to call into the runtime - naturally any runtime functions that result in a status change could just call the appropriate functions to set the process status before returning control to the generated code, _but_ they'd still want to update the thread local as well.

## RE: Calling Convention, etc.

I think one of the things making this more confusing is that the way the handwritten Rust code (e.g. spawn-chain) works doesn't bear much resemblence to how code gets generated by our backend:

- Codegen uses the native stack + registers for locals, no stack_push/pop
- The types used in the current scheduler for `code` are not FFI-safe, we can't use `Result` or return our exception types by value - we have to be careful in general about what we return by value via FFI, basically everything should be the equivalent of `Result<(), Signal>` or `Result<Term, Signal>`, where `Result` here is our own FFI-safe result type, and in this example I'm using it as the signaling mechanism as well, but it could just as easily be `bool` and `Option<Term>`, the former for void functions, and the latter for value-returning functions where we just signal something went wrong by using the false/none value. To preserve stack traces from the anyhow errors we generate though, another option is to store the current exception value in the process, or on the heap somewhere, and return a pointer to that error as the `Err` variant of our Result. Since a runtime failure would result in the generated code unwinding to the scheduler (or perhaps on some platforms jumping straight back to the scheduler), that error pointer would be the same error that would have been propagated anyway. In short, I don't believe we sacrifice the nice traces in this model.
- We can do a lot in the generated code, and could do even more, without having to call into the runtime to do so; constructing values, checking types, unboxed math, equality for trivial cases, etc. It's worth keeping in mind that we _want_ to do as much as possible via code generation, rather than depending on a large runtime, since the more we can generate code for, the more runtime code can be written in pure Erlang. But getting back to the point - we can't assume that generated code will be using all of the runtime infrastructure, or using it all of the time. Initially we'll be more dependent on the runtime of course, but over time that will be less true.

That said, some aspects are similar:

- We will check the result of runtime calls, using whatever signaling mechanism we end up with, before invoking the current continuation. This is similar to how the exception handling code you have checks whether or not a runtime NIF raised an error before invoking the next code pointer.
- If the current continuation is null, then the code is done executing, and unwinds back to the scheduler

> Are we getting rid of the push_stack and pop_stackn function since the LLVM code may have put the Erlang term variables in true registers on native? If so, I'll need to either remove or modify their usage in stuff like the native_implemented_function's code function that peeks the values from the stack for native and pops them all when it is safe to no longer worry about re-entrancy.

Just in case it gets lost in the noise above, yes, these functions have no use with the codegen backend, since it uses the native stack exclusively. Anything that can't go on the native stack, spills to the heap. The generated code will make use of the alloc_layout builtin to construct values for calling into runtime, or for moving things into the process heap.

> On that note, how are you handling re-entrancy with stack values and potential calls for GC? Are you just peeking or is stuff off the stack? I had to reason that all by hand and add some fallible unwraps in spawn-chain.

Can you provide more specifics, or how it manifested in spawn-chain? There isn't a path for re-entrancy when garbage collection is invoked from the generated code; the collector has to return control to the caller. Additionally, stack values in the caller are not allowed (at least in this model) to be referenced from a callee; they have to be explicitly passed as arguments, or promoted to the heap; so when returning control to the scheduler during a yield, live stack values at the yield point get stored in the continuation frame, and are restored when resuming the process via that frame.

**Comment by KronicDeth** [comment]
> Can you provide more specifics, or how it manifested in spawn-chain?

It had to do with Rust's `?` returning with an `Err(Alloc)` after `stack_pop()`ing the arguments, but before a new Code pointer was set, so the continuation pointer was still the function entry point, but the function arguments were gone.  If the generated code makes a new continuation frame when the `Err(Alloc)` equivalent happens and doesn't keep it as the function or label entry point it will be fine.

**Comment by bitwalker** [comment]
Closing this as we're already past the initial integration stage
