### ISSUE TITLE
Lumen tests fail because libLLVM-12-lumen-10.0.0 is not available

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#465]
Neither the macOS (https://github.com/lumen/lumen/runs/956919116) or the Linux (https://github.com/lumen/lumen/runs/956918971) can find libLLVM-12-lumen-10.0.0.so:

 --- stderr
158
llvm-config: error: libLLVM-12-lumen-10.0.0.dylib is missing
159
thread 'main' panicked at 'command did not execute successfully: "/Users/runner/.local/share/llvm/lumen/bin/llvm-config" "--link-shared" "--libs" "--system-libs" "aarch64" "arm" "asmparser" "bitreader" "bitwriter" "core" "instrumentation" "ipo" "linker" "lto" "webassembly" "x86"
160
expected success, got: exit code: 1', compiler/llvm/build.rs:306:9
161
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 --- stderr
159
llvm-config: error: libLLVM-12-lumen-10.0.0.so is missing
160
thread 'main' panicked at 'command did not execute successfully: "/opt/llvm/bin/llvm-config" "--link-shared" "--libs" "--system-libs" "aarch64" "arm" "asmparser" "bitreader" "bitwriter" "core" "instrumentation" "ipo" "linker" "lto" "webassembly" "x86"
161
expected success, got: exit code: 1', compiler/llvm/build.rs:306:9

@bitwalker, do  you need to push and upload a new release of LLVM to make this work?  I can't find that file locally either in ~/.local/share/llvm/lumen/** or target/debug/**.

**Comment by bitwalker** [comment]
I think we actually want to build statically in CI, even though it takes longer, since we could eventually start producing releases from CI, and those we'll want to be statically linked. The dynamic linking is available for local development to avoid the long linking times for the compiler due to all the work the linker has to do. I just forgot to export the right env vars in the CI workflows not invoking `make build` to use the static build (`make build` will always try to build statically, whereas `make build-shared` will not).

**Comment by KronicDeth** [comment]
@bitwalker but I can't build non-statically locally either.  How do I fix that?
